# Generated by Django 2.0.3 on 2018-07-04 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('title_content', models.TextField()),
                ('detail_content', models.TextField()),
                ('date_added', models.DateField(auto_now=True)),
                ('card_image', models.ImageField(default='default.png', upload_to='career_cards/')),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Cards',
                'verbose_name_plural': 'Cards',
            },
        ),
        migrations.CreateModel(
            name='CareerTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interesting_at_rs_title', models.CharField(max_length=50)),
                ('position_title', models.CharField(max_length=50)),
                ('map_title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('job_category', models.CharField(max_length=80)),
                ('resume', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResumeSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(max_length=100)),
                ('section_body', models.CharField(max_length=150)),
                ('button_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Vacancies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=255)),
                ('link', models.URLField(default='https://merojob.com/')),
                ('number', models.PositiveIntegerField()),
                ('deadline', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Vacancies',
                'verbose_name_plural': 'Vacancies',
            },
        ),
    ]
